# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d45e201a8da762f27ebe0b79c1ec73bf8af6fefd6f8d8207031e20e862c24d90cb882e01ccd913718d5eb91b8352abc1bfa23db5851661a4a5daa6dd2c7aefd

test:
  secret_key_base: a70a0fb376a67320faeb2368e56c024b832721e55be7df6ab8985c1cd57be8f4cd7f25ff9db45c786e4b4270b676ffb72db18bd31bbe966515924031044f9b5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
